// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg3mQwYbFGIfKC5wRYk4m5eWfjfF7OmZo',
    appId: '1:54337288155:web:190a76aedf659332a819fe',
    messagingSenderId: '54337288155',
    projectId: 'chats-a26f8',
    authDomain: 'chats-a26f8.firebaseapp.com',
    storageBucket: 'chats-a26f8.firebasestorage.app',
    measurementId: 'G-C4L8MSXNRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7agXr4VNOIr3rgDD41t__WfLV7Bn0d1E',
    appId: '1:54337288155:android:63554fb6707a440ca819fe',
    messagingSenderId: '54337288155',
    projectId: 'chats-a26f8',
    storageBucket: 'chats-a26f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaOyfjKxFLPZkWS5Pw6hDsr8H4jJQLAIY',
    appId: '1:54337288155:ios:f49c189105c44f7aa819fe',
    messagingSenderId: '54337288155',
    projectId: 'chats-a26f8',
    storageBucket: 'chats-a26f8.firebasestorage.app',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaOyfjKxFLPZkWS5Pw6hDsr8H4jJQLAIY',
    appId: '1:54337288155:ios:f49c189105c44f7aa819fe',
    messagingSenderId: '54337288155',
    projectId: 'chats-a26f8',
    storageBucket: 'chats-a26f8.firebasestorage.app',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg3mQwYbFGIfKC5wRYk4m5eWfjfF7OmZo',
    appId: '1:54337288155:web:fe526ec1cf2c07aca819fe',
    messagingSenderId: '54337288155',
    projectId: 'chats-a26f8',
    authDomain: 'chats-a26f8.firebaseapp.com',
    storageBucket: 'chats-a26f8.firebasestorage.app',
    measurementId: 'G-7M4HCXTZGF',
  );
}
